declare global {
	interface AuthDatabase {
		host: string;
		name: string;
		username: string;
		password: string;
	}

	interface Auth {
		token: string;
		database: AuthDatabase;
	}

	interface Constants {
		prefix: string;
		channels: object;
		roles: object;
		messages: object;
		guild: string;
		emojis: object;
	}
	// Generated by https://quicktype.io

	interface Languages {
		blacklisted: string;
		errors: LanguageErrors;
	}

	interface LanguageErrors {
		internal: string;
	}
}
export {};
