declare global {
	interface AuthDatabase {
		host: string;
		name: string;
		username: string;
		password: string;
	}

	interface Auth {
		token: string;
		database: AuthDatabase;
	}

	interface Constants {
		prefix: string;
		channels: object;
		roles: object;
		messages: object;
		guild: string;
		emojis: object;
	}
	// Generated by https://quicktype.io

	export interface Languages {
		blacklisted: string;
		commands: LanguageCommands;
		errors: LanguageErrors;
	}

	export interface LanguageCommands {
		help: LanguageHelp;
		ping: LanguagePing;
	}

	export interface LanguageHelp {
		title: string;
		description: string;
		sent: string;
	}

	export interface LanguagePing {
		calculating: string;
		pong: string;
	}

	export interface LanguageErrors {
		internal: string;
	}

}
export {};
